name: publish to nuget
on:
  push:
    branches:
      - master # Default release branch
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      # Publish
      - name: publish on version change
        id: publish_nuget
        uses: Mbucari/publish-nuget@v2.5.6
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: AAXClean.csproj
          
          #BUILD_CONFIGURATION: Release
          
          #BUILD_PLATFORM: x64
          
          # NuGet package id, used for version detection & defaults to project name
          PACKAGE_NAME: AAXClean
          
          # Filepath with version info, relative to root of repository & defaults to PROJECT_FILE_PATH
          # VERSION_FILE_PATH: Directory.Build.props
          # Regex pattern to extract version info in a capturing group
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          
          # Useful with external providers like Nerdbank.GitVersioning, ignores VERSION_FILE_PATH & VERSION_REGEX
          # VERSION_STATIC: 0.1.0
          # Flag to toggle git tagging, enabled by default
          # TAG_COMMIT: true
