# validate.yml
# Validates that Libation will build on a pull request or push to master. 
---
name: validate

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      project_file: ./src/AAXClean/AAXClean.csproj
      nuspec_file: ./AAXClean.nuspec
    secrets:
      nuget_token: ${{ secrets.AAXCLEAN_NUGET_API_KEY }}
